#!/bin/bash

# THIS SCRIPT COPIES A ROSBAG TO CPR INTERNAL SERVERS FOR ANALYSIS IF POSSIBLE
TEMPDIR=$(mktemp -d --tmpdir jackal_circle_test.XXXX)
BAG_FILE=${TEMPDIR}/${HOSTNAME}_test
DURATION=60

ROSTOPIC_OUTPUT=$(rostopic list)
if [[ "$?" != "0" ]]; then
  echo "ROS appears not to be running. Please start ROS service:"
  echo "sudo service ros-start"
  exit 1
fi

rospack find rosbag > /dev/null
if [[ "$?" != "0" ]]; then
  echo "Unable to find rosbag record. Is the ROS environment set up correctly?"
  exit 1
fi

rospack find jackal_base > /dev/null
if [[ "$?" != "0" ]]; then
  echo "Unable to find jackal_base. Are the Jackal packages built and in the ROS_PACKAGE_PATH?"
  exit 1
fi

read -n1 -r -p "Jackal will require at least x meters in all direction to perform this test, press any key to continue"
echo


rosbag record -a -o $BAG_FILE --duration $DURATION > /dev/null &
ROSBAG_PID=$!
echo "Started rosbag record, duration $DURATION seconds, pid [${ROSBAG_PID}]"
sleep 2

rostopic pub /jackal_velocity_controller/cmd_vel geometry_msgs/Twist "linear:
  x: 0.3
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.3" -r 15 & > /dev/null
ROSTOPIC_PID=$!
echo "Started motion commands, pid [${ROSTOPIC_PID}]"

sleep 2

echo "Test underway."

for i in $(seq 0 ${DURATION}); do
  echo -en "\rTime remaining: $((${DURATION}-i))  ";
  sleep 1
done
echo

echo "Shutting down motion command publisher."
kill $ROSTOPIC_PID


sleep 2

echo "Waiting for rosbag to shut down."


sleep 2

ping -c 1 10.27.0.1 > /dev/null
if [[ "$?" != "0" ]]; then
  echo "Unable to connect to Clearpath Internal servers, copying rosbag to home directory, please send to support@clearpathrobotics.com for analysis"
  cp ${BAG_FILE}* /home/administrator
else
  echo -n "Enter your Clearpath Username > "
  read username
  smbclient //ipython/notebooks -W clearpath -U ${username} -c  'cd  \mcote\Jackal_Inspection_Bags ; lcd '${TMPDIR}';recurse ON;prompt OFF; mput *'
fi
